# Whirlwind Tour of Python
## Usman Nazir

#### sources: International Summer School on Deep Learning, CIIT Data Science Workshop

# Introduction - How do I install?

* Run Locally
    1. Install Python
        * Python
        * Anaconda
    2. Run...
        * ... as a script
        * ... in a Notebook
    
* Run Remotely
    * Google Colab

## Introduction | Run Locally

* If you are on Linux or Mac you should have Python availabile
* For Windows users: https://www.python.org/downloads/windows/ (Latest Python 3)

__...but either way you should really use Anaconda__

* It's a Python distribution - manage not only Python packages, but also additional libraries / drivers
* Get it from: https://www.anaconda.com/products/individual
* `conda install` vs `pip install`

* Run as a script
* or use Jupyter Notebook

```bash
pip install jupyter

# or even better:
conda install jupyter
```

## Introduction | Run Remotely | Google Colab

* Available at https://colab.research.google.com/
* It's free! You only need a Google account to access
* Offers different environment: CPU / GPU / TPU
* Resources are not guaranteed
* Avoid hogging resources - you can get lower priority in the future if requested resources are not actievely used!

* When running Google Colab you get your own virtualized environment - you can install packages
* The environment will be cleaned upon exiting - make your life easier and install all additional dependencies in the first cell.

* Example command to install Python's wget:

    ```bash
    !pip install wget
    ```
    Verify:

    ```python
    import wget
    wget.__version__
    ```

# 🐍 Python

<center>
    <img src="https://imgs.xkcd.com/comics/python.png" alt="Python: https://xkcd.com/353/" />
    <div><i>Source: <a href="https://xkcd.com/353/" target="_blank">XKCD 353</a></i></div>
</center>

Whirlwind tour of Python
========================
* Object Oriented
* however #1 - no explicit encapsulation: "After all, we're all consenting adults here."
* however #2 - no class interface, only (multi)inheritance
* multi-paradigm
* interpreted
* strongly typed
* dynamically typed
* 🦆 duck typing
* garbage collector
* designed for code clarity
* object introspection
* interactive mode (terminal / IPython)
* interfaces to many popular programming languages:
    * C++
    * Java
    * .NET
    * and many others
* has it's own package manager - pip & easy_install
* before writing a library - check if it exists

# Python | Variables

In [13]:
# Dynamically typed language: types are dynamically inferred. 
# This means, for example, that we can assign any kind of data to any variable:
a = 1
type(a)

int

In [14]:
a = 'four'
type(a) # We can ask the variable for its type

str

What do you think about not declaring variable explicitly?

In [11]:
# Multiple assignments
b = c = d = 10 
print(b,c,d)
e, f, g = 12,'23',12.01
print(e,f,g)

10 10 10
12 23 12.01


In [12]:
# Please check the type of f and g ???

# Strings
Now we will create some text strings, in a couple of ways.

In [15]:
s = 'hello'
s

'hello'

In [16]:
s = "hello"

Notice that both single quotes and double quotes give us the same string. You can pick whichever style that you like. We can also create multi-line strings, with embedded newline characters.

We can concatenate strings together, and we can also index specific characters in the string. Negative indices count from the end of the string.

In [17]:
s = "hello " + 'LUMS'
s

'hello LUMS'

In [18]:
s[0]

'h'

In [19]:
s[-1]   # accessing the last element

'S'

# Slicing


Slicing is used to extract a subsequence out of your sequence, and has a special notation in Python:

    var[lower:upper:step]

The element which has index equal to the lower bound is included in the slice, but the element which has index equal to the upper bound is excluded, so mathematically, the slice is `[lower, upper)`.  If you think of the indices as being between the elements, then this mentally works very nicely, as we'll see.

The `step` argument is optional, and indicates the strides between elements in the subsequence, so a step of 2 takes every second element.

As an example, let's extract elements 0 through 3:


In [21]:
s[0:3] # 1 is included but 3 is excluded 

'hel'

In [22]:
s[:3]

'hel'

In [23]:
s[-3:]

'UMS'

In [25]:
s[:-3]

'hello L'

In [26]:
len(s)

10

### String Operations

In [27]:
s.split()

['hello', 'LUMS']

In [29]:
s.replace("hello", "Welcome")

'Welcome LUMS'

In [30]:
s.upper()

'HELLO LUMS'

In [31]:
str(1) # Number/String Conversions

'1'

In [33]:
Name = 'Data Science in Practice'
# Write a command to extract 'Science in Practice'

Explore the following funciton of strings ???

- lower()
- capitalize()
- endswith()
- join()
- strip()

use e.g. s.endswith?

In [35]:
# There are many other methods on strings, and Python's dir() function will list all the methods on an object:
dir(s)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'zfill']

## Python | Data Structures | List

Lists
----------

List in Python are an ordered sequence of any kind of object, and are one of the workhorse data structures.

List Objects
------------

You create a list by putting square brackets around a comma-separated list of other Python items:

In [36]:
lst = [1, 2.0, 3, 'LUMS']
print(lst)

[1, 2.0, 3, 'LUMS']


In [37]:
lst * 3 

[1, 2.0, 3, 'LUMS', 1, 2.0, 3, 'LUMS', 1, 2.0, 3, 'LUMS']

In [38]:
lst + lst

[1, 2.0, 3, 'LUMS', 1, 2.0, 3, 'LUMS']

In [39]:
lst[0]

1

In [40]:
lst[-1]

'LUMS'

In [41]:
len(lst)

4

In [42]:
type(lst)

list

In [44]:
lst = [0]*10
print(lst)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


## Range

The `range()` built-in function creates a list of integers, and is used a lot in Python because the `for` loop operates over lists.

The simplest way to use the range function is to just specify the number of elements or, in another way of thinking about it, specify the stop value:

In [49]:
my_list = list(range(10))
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [52]:
my_list = list(range(3,10,2))
my_list

[3, 5, 7, 9]

In [53]:
# how we can crate a list of integers [2, 4, 6, 8] using range  ?

In [57]:
my_list[2]
my_list[-1]
my_list[1:3]
my_list[2:]
my_list[:]

[3, 5, 7, 9]

In [62]:
#2D - we can create a 2d list
r = 4
c = 5
list2d = [[0]*c for _ in range(r)]  # this is called list comprehension
#print(list2d[0])
#print(list2d[0][3])

a = []
for y in range(r):
    a.append([])
    for x in range(c):
        a[-1].append((x+1)*(y+1)) # we can also pre-pend elements, but it's an expensive operation
print(a)
print(a[1:3])
print(a[1:3][1:3]) # won't work :(
# instead, you have to access indices in first dim like this:
print(a[1][1:3]) 
print(a[2][1:3]) 

[[1, 2, 3, 4, 5], [2, 4, 6, 8, 10], [3, 6, 9, 12, 15], [4, 8, 12, 16, 20]]
[[2, 4, 6, 8, 10], [3, 6, 9, 12, 15]]
[[3, 6, 9, 12, 15]]
[4, 6]
[6, 9]


In [72]:
#### Operations on Lists
### We've seen the generic length function in Python and it works on any kind of sequence, including lists:
lst = [1, 2.0, 3, 'LUMS']
lst.append('Class')
lst

[1, 2.0, 3, 'LUMS', 'Class']

In [68]:
del lst[1]
lst

[1, 3, 'LUMS', 'Class']

In [69]:
1 in lst

True

In [70]:
2 in lst

False

- how we can show the method of lst and explore some of these
    - 'append'
    - 'count'
    - 'extend'
    - 'index'
    - 'insert'
    - 'pop'
    - 'remove'
    - 'reverse'
    - 'sort'

## Set
### Python also provides the `set` data structure, which can be created using curly brackets.

In [73]:
a = {1, 2, 3, 4}
a

{1, 2, 3, 4}

In [74]:
b = {2, 3, 4, 5}
b

{2, 3, 4, 5}

In [76]:
b.add(1)
b

{1, 2, 3, 4, 5}

In [77]:
a & b  # Intersection

{1, 2, 3, 4}

In [78]:
a | b # Union

{1, 2, 3, 4, 5}

In [79]:
a ^ b # symmetric difference

{5}

In [80]:
a - b

set()

## Python | Data Structures | Dictionaries

If you're familiar with the computer science "hash" or "map" data structures, a dictionary is essentially the Python equivalent of those.

For those unfamiliar with Python dictionaries, we can use an actual dictionary as a mental model.  In a dictionary you have words, and those words have definitions that are associated with them. You might have multiple definitions, but they are all associated with one word's entry in the dictionary.

This maps to the data structure very well: each entry is a key-value pair, where the keys are the words, and the values are the definitions.  If there are multiple definitions, you might instead have a list of definitions instead of a single definition for the value, but the idea is the same.

So in Python we can create an empty dictionary with a pair of braces (curly brackets):

In [4]:
pets = {'dogs':5, 'cats':4}
pets

{'dogs': 5, 'cats': 4}

In [83]:
len(pets)

2

In [92]:
pets['dogs']

7

In [93]:
pets['dogs'] += 2
pets

{'dogs': 9, 'cats': 4}

In [94]:
pets['fox'] = 3
pets

{'dogs': 9, 'cats': 4, 'fox': 3}

In [96]:
# You can ask for the list of keys, of key-value pairs, or just the values.
pets.keys()

dict_keys(['dogs', 'cats', 'fox'])

In [97]:
pets.items()

dict_items([('dogs', 9), ('cats', 4), ('fox', 3)])

In [88]:
d = {}
d = {'a':1 , 'b':2, (0,0): 123}

f = {key: key**2 for key in range(5) if key%2==0}
f

{0: 0, 2: 4, 4: 16}

In [89]:
d['a']

1

In [90]:
for key, value in d.items():
    print(key, value)

a 1
b 2
(0, 0) 123


Can we have a dictionary inside a dictionary?

## Python | Operators


In [106]:
print(3**2)
print(3//2) 

9
1


# NumPy

## NumPy

* linear algegra library for python
* main building block for data-oriented libaries
* It's fast
* Even faster if you install it using Anaconda

```bash
pip install numpy
# or
conda install -y numpy

In [126]:
import numpy as np

## NumPy | Array vs Python List

<center>
    <img src="https://jakevdp.github.io/PythonDataScienceHandbook/figures/array_vs_list.png" />
    <i>Source: <a href="https://jakevdp.github.io/PythonDataScienceHandbook/02.01-understanding-data-types.html" target="_blank">jakevdp.github.io/PythonDataScienceHandbook/02.01-understanding-data-types.html</a></i>
</center>

# Python | Data Structures | NumPy Array

By now, we're pretty use to lists being the workhorse sequential data structure in Python. It's great for many things, but it turns out that another data structure, the NumPy array, provides a different set of functionality that is really useful -- especially for numeric computations.

Here we start with a list, and illustrate the difference in syntax for mathematical operations on a list and an array.

Imagine you want to add 1 to every element in a sequence. Here is a comparison between doing this with an array and a list.

Let's look at a list

In [117]:
a = [1, 2, 3, 4]
#If you add 1 to a list, you get an error because you can't add list and int types.
a+1

TypeError: can only concatenate list (not "int") to list

In [118]:
# This will work, but it is a bit cryptic to the uninitiated:
[val + 1 for val in a]

[2, 3, 4, 5]

In [127]:
# But if we convert `a` to a NumPy `array`, then it does work:
a = np.array(a)
a+1

# This is the first thing that the array provides: when you perform a mathematical operation on an array, 
# the operation is performed on every element of the array.  
# So the result is 1+1 is 2, 2+1 is 3, 3+1 is 4 and 4+1 is 5.


array([2, 3, 4, 5])

# Operations on two Arrays
------------------------

NumPy always carries out element-by-element operations when operating on two arrays.  Here are several examples with `+`,`*`, and `**` operators.

Let's create another array `b`:

In [128]:
b = np.array([2, 3, 4, 5])

In [131]:
# They both have 4 elements.  If we add a and b:
# then the operation is performed element-by-element: 1+2 is 3, 2+3 is 5, 3+4 is 7 and 4+5 is 9.
a+b

array([3, 5, 7, 9])

In [132]:
# This doesn't just work for addition.  You can multiply:
a*b

array([ 2,  6, 12, 20])

In [133]:
# You can exponentiate:
a**b

array([   1,    8,   81, 1024])

All operations are performed element-by-element.

## NumPy | Creating Arrays

In [134]:
import numpy as np

my_list = [0,1,2,3,4]
np.array(my_list)

my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

np.arange(0, 10).reshape(2,5)

np.zeros((3,3))

np.ones((3,3))

np.linspace(0,10,101)

np.eye(4) # NxN as identity matrix must be square,

np.random.rand(2) # will populate given range with a population of uniform distribution over 0 to 1
np.random.rand(2,2) # weirdly enough, for more dimensions we do not pass tuple, but instead we just add another argument

np.random.randint(0,10)  # will draw a single int from given range
np.random.randint(0,10,(3,3)) # will draw a 3x3 array from given range

np.random.randn(4) # draw N samples for normal distribution centered around 0
np.random.randn(4,4)

array([[ 1.08087037, -0.76176349,  0.86504572, -0.59883839],
       [ 2.07755951, -0.08504213,  0.40034572, -0.9767852 ],
       [-1.85686917,  0.75452808, -0.53391683, -0.51560202],
       [-1.40520258, -1.33921143, -0.10856839,  0.48210568]])

## NumPy | Dimensions

In [135]:
np.array([1,2,3])
a = np.array([[1,2,3], [4,5,6]])

# ndarray.ndim
# the number of axes (dimensions) of the array.
print(a.ndim)

# ndarray.shape
# the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension.
# For a matrix with n rows and m columns, shape will be (n,m). 
# The length of the shape tuple is therefore the number of axes, ndim.
print(a.shape)

# ndarray.size
# the total number of elements of the array. This is equal to the product of the elements of shape.
print(a.size)

2
(2, 3)
6


## NumPy | Data types

* NumPy arrays are homogeneous (elements of the same type)

In [136]:
l = np.array([1,2])
print(l, l.dtype)

l = np.array([1.0,2.0])
print(l, l.dtype)

l = np.array([1.0,2.0], dtype=np.int16)
print(l, l.dtype)

[1 2] int64
[1. 2.] float64
[1 2] int16


## NumPy | Indexing 

In [137]:
mat = np.arange(9).reshape(3, 3)
print(mat)

print(mat[0][1]) # while we can use syntax just like in python's list
print(mat[0,1])  # a coma-seperated indices became a golden standard for getting a value out of numpy;s array
print(mat[:,1])
print(mat[1,:])
print(mat[:2,1:])
print(mat[:]) # to access all elements

[[0 1 2]
 [3 4 5]
 [6 7 8]]
1
1
[1 4 7]
[3 4 5]
[[1 2]
 [4 5]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


## NumPy | Boolean Masking
Boolean masking is one of my favorite party tricks that i like to use to impress people at the LUMS PDC.

When we index arrays with integers we are explicitly providing the indices to pick. With boolean indices the approach is different; we explicitly choose which items in the array we want and which ones we don’t.

The most natural way one can think of for boolean indexing is to use boolean arrays that have the same shape as the original array:

```python
mat = np.arange(12).reshape(3, 4)
mat
mat.shape
b = mat>4
b
b.shape
# now that we have the mask, numpy allows us to use it as an index:
mat[b]
# notice that the shape is different.
mat[b].shape
# When you apply the mask the information about the shape does not
# get carried over to the filtered array, as in most cases you would end up with jagged arrays and numpy
# does not support that kind of thing.

# different forms of expressions can be used to create a mask,
# for instance if we want to select all elements which multiplied by 2 are equal to the element to the 2nd power,
# we can use:
mat[ (mat*2) == (mat**2) ]

# now, we can also inverse the mask by either changing the condition we defined above,
# or we can simply use logical not:
mat[np.logical_not(b)]
# now that we have access to all elements smaller than 4, let's reset them to zero
mat[np.logical_not(b)] = 0
mat
# but how did it happen, that we managed to assign a single value to multiple elements? Let's check it out on the next slide!
```

In [140]:
mat = np.arange(12).reshape(3,4)
print(mat)

b = mat > 4

print(mat[b])

print(mat[b].shape)

print(mat[(mat*2) == (mat**2) ])

print(mat[np.logical_not(b)])

mat[np.logical_not(b)] = 0
print(mat)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 5  6  7  8  9 10 11]
(7,)
[0 2]
[0 1 2 3 4]
[[ 0  0  0  0]
 [ 0  5  6  7]
 [ 8  9 10 11]]


## NumPy | Broadcasting
Arithmetic operations on arrays are usually done on corresponding elements. If two arrays are of exactly the same shape, then these operations are smoothly performed.

The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. See <a href="https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html">Broadcasting</a> for more information on numpy.

```python
a = np.arange(11)
a
b = a[:5]
b
b[:] = 999 # mind the colon - it means we grab all elements. Without using it we will simply convert variable b
# from being a numpy array to being just an integer 999. This is the example of broadcasting. We take array and we
# apply an operation to it - in this case assignment - using an object of a different shape. In this case the
# 999 will be broadcasted into the array of the same shape as the object 'a', and will be then applied in 1-1 
# matching between the indices of two array.
b

# i will point one issue here, with what we have just done. You see, to avioid being a memory hog when 
# dealing with larger matrices, numpy handles matrices as references, and when we grabbed subarray of 'a',
# we did not create a new array, we just got few references to the first 5 objects. and as such if we display 'a':
a
# to avoid this issue we can use .copy() to create a new instance with same values
b_copy = a[:5].copy()
b_copy[:] = 33
b_copy
a

# we can use broadcast to do all kinds of things: multiply, add, subtract, divide.
# we can do it on all elements, a filtered subset or on rows or columns
a = np.ones((3,3))
a
a * [1,2,3] 
a * [[1],[2],[3]]
a * [1,2,3] * [[1], [2], [3]]
# but we have to remember that that we can only use objects that can be scaled up to the other's size,
# so things like same number of columns or rows are important
# a * [2,2] # this will cause an error
```

In [144]:
a = np.arange(11)
print(a)
b = a[:5]
print(b)
b[:] = 999 # mind the colon - it means we access all elements, without it we would just create new object 'b'
print(b)

# when we grabbed subarray of 'a',
# we did not create a new array, we just got few references to the first 5 objects.
print(a)
# to avoid this issue we can use .copy() to create a new instance with same values
b_copy = a[:5].copy()
b_copy[:] = 33
print(b_copy)
print(a)

a = np.ones((3,3))
print(a)
print(a * [1,2,3]) 
print(a * [[1],[2],[3]])
print(a * [1,2,3] * [[1], [2], [3]])

[ 0  1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4]
[999 999 999 999 999]
[999 999 999 999 999   5   6   7   8   9  10]
[33 33 33 33 33]
[999 999 999 999 999   5   6   7   8   9  10]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]
[[1. 2. 3.]
 [2. 4. 6.]
 [3. 6. 9.]]


## NumPy | Operations


In [146]:
np.random.seed(101)
a = np.random.randint(1,3,(2,2))
print(a)
print(a.min())
print(a.max())
print(a.argmin())
print(a.argmax())

b = np.random.randint(1,3,(2,2))
print(b)

print(a*5)
print(a*b) # it's an element wise multiplication
print(a.dot(b))

[[2 2]
 [2 1]]
1
2
3
0
[[2 2]
 [2 2]]
[[10 10]
 [10  5]]
[[4 4]
 [4 2]]
[[8 8]
 [6 6]]


# Python | Conditional Statements
-------------

### If statements

The simplest sort of way of controlling execution is to decide whether or not
a particular piece of code should be executed or not, based upon some
condition.  This could include:

* computing a particular value for a function in the special case where
  `x = 0`

* testing if an input is good, and only computing values if it is

* executing different pieces of code depending on a command string read from a file
  
In each of these cases, we execute the code *if* some condition holds, so the
statement in Python (and many other languages) that lets us do this is called
the `if` statement.

The simplest form of the `if` statement looks like this:

In [148]:
x = 0.5

if x > 0:
    print("Hey!")
    print("x is positive")

Hey!
x is positive


In [149]:
x = -0.5

if x > 0:
    print("Hey!")
    print("x is positive")
    print("This is still part of the block")
print("This isn't part of the block, and will always print.")

This isn't part of the block, and will always print.


In [150]:
x = 0

if x > 0:
    print("x is positive")
elif x == 0:
    print("x is zero")
else:
    print("x is negative")

x is zero


In [151]:
# to check the elements in the list
#mylist = [3, 1, 4, 1, 5, 9]
mylist = []
if mylist:
    print("The first element is:", mylist[0])
else:
    print("There is no first element.")

There is no first element.


# Python | Loops

When programming, you want to be able to repeatedly execute chunks of code
without having to manually duplicate the code.  Being able to repeat a set of
instructions in a controlled manner is perhaps the most important function of any
sort of automation, and being able to write code to execute something a
million times as easily as writing code to execute something three times is
important.

Python implements a number of looping constructs, and in this lecture we'll
discuss the `while` loop and the `for` loop.

## While loop


The `while` loop is the simplest form of loop in Python.  It is similar to an `if`
statement, in that it evaluates a test which evaluates to `True` or `False`.
Unlike the `if` statement, however, a `while` statement doesn't just execute the following
block of code once, it executes it over and over, re-evaluating the test
before each repetition.  When the test evaluates to `False`, the loop will stop
executing, and execution will continue with the next section of code.  Just
like the `if` statement, indentation determines which lines of code are
associated with the `while` statement.

A simple example of a `while` loop might look something like this:

In [152]:
i = 0
total = 0
while i < 100:
    total += i
    i += 1
print(total)

4950


In [154]:
# 'For' loop
for i in range(5):
    print(i)

0
1
2
3
4


In [155]:
line = '1 2 3 4 5'
fields = line.split()
fields

['1', '2', '3', '4', '5']

In [156]:
#fields = [1,2,3,4,5]
total = 0
for field in fields:
    total += int(field)
total

15

In [157]:
#List Comprehension: which is a compact way of writing many loops.
numbers = [int(field) for field in fields]
numbers 

[1, 2, 3, 4, 5]

In [158]:
sum(numbers)

15

### Break and Continue

Both for and while statements can have the flow modified with the `break` and
`continue` statements.

If execution hits a `continue` statement, then the execution will jump
immediately to the start of the next iteration of the loop.  This is useful if
you want to skip occasional values:

In [159]:
# Lets print even elements from the given list
values = [7, 6, 4, 7, 19, 2, 1]

for i in values:
    if i % 2 != 0:
        # skip odd numbers
        continue
    print(i)

6
4
2


In [160]:
# Print the elements of the list until you encounter 'stop'.
command_list = ['start', 'process', 'process', 'process', 'stop', 'start', 'process', 'stop']

while command_list:
    command = command_list.pop(0)
    if command == 'stop':
        break
    print(command)

start
process
process
process


# Python | Functions


In [163]:
def add(x,y):
    """ Add two values"""
    a = x+y
    return a
add(4,5)

9

In [161]:
# Python Scope
#x = 4

def fun():
    global x
    x = x+1
    return x

fun()

1

In [ ]:
# Python Anonymous Functions
def pow2(x):
    return x**2

print(pow2(2))

pow2_lambda = lambda x: x**2
print(pow2_lambda(2))

l = list(range(10))
print(l)

print(list(filter(lambda x: (x%2==0), l)))
print(list(map(lambda x: x**2, l))) 

In [162]:
## Python | \*args and \*\*kwargs
a = [1,2,3]
print(a[0], a[1], a[2])

raw_data = ['label', 'width', 'height', 'depth']
(label, *data) = raw_data

print(label)
print(data)

from random import randint
def roll(*args):
    return sum(randint(1, die) for die in args)

print(roll(6, 6, 6, 6))

# **kwargs

def data2xml(label, **attr):
    attr_list = ['{}="{}"'.format(name, value) for name, value in attr.items()]
    print('<{} {} />'.format(label, ' '.join(attr_list)))

data2xml('my_label', width=10, height=20)

1 2 3
label
['width', 'height', 'depth']
16
<my_label width="10" height="20" />


# Python | Classes

Now lets create a class. In Python, every class should derive from object. 
Our class will describe a person, with a name and an age. We will supply a constructor, and 
a method to get the full name.

In [1]:
class Person(object):
    # Initializing
    def __init__(self, first, last, age):
        self.first = first
        self.last = last
        self.age = age
    
    # Deleting (Calling destructor) 
    def __del__(self):
        print('Destructor called, person deleted.')

    def full_name(self):
        return self.first + ' ' + self.last    

In [2]:
# Now we can create an instance of a Person, and work with the attributes of the class.
person = Person('Muhammad', 'Kamran', 35)
print(person.first)
print (person.age)
print(person.full_name())

Muhammad
35
Muhammad Kamran


In [6]:
person.pet = pets
person.pet
# to delete the object explicitly
del person

Destructor called, person deleted.


# Read test.txt file and perform the following task

1) find count of unique words

2) find unique words and their frequencies

3) convert all text into lower case then find count of unique words

4) convert all text into lower case and find unique words and their frequencies

5) sort the words by frequencies and store the results in freq.txt file

6) sort the words by alphabatical order and store results in words.txt file